CREATE TABLE TGT_BANK_TRANSACTION (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER,
    TRANSACTION_AMOUNT NUMBER(12,2),
    TRANSACTION_DATE DATE,
    TRANSACTION_TYPE VARCHAR2(20),

    CONSTRAINT FK_ACCOUNT_1
    FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE TGT_REJECT_TRANSACTIONS (
    TRANSACTION_ID NUMBER,
    ERROR_MESSAGE VARCHAR2(300),
    REJECT_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TGT_FRAUD_ALERT (
    ALERT_ID NUMBER PRIMARY KEY,
    TRANSACTION_ID NUMBER,
    FRAUD_REASON VARCHAR2(200),
    FRAUD_SCORE NUMBER(5,2),
    ALERT_STATUS VARCHAR2(20)
);

CREATE TABLE TGT_RECONCILIATION_ISSUE (
    ISSUE_ID NUMBER PRIMARY KEY,
    TRANSACTION_ID NUMBER,
    SOURCE_SYSTEM VARCHAR2(100),
    ISSUE_DESCRIPTION VARCHAR2(300),
    ISSUE_STATUS VARCHAR2(20)
);

SELECT * 
FROM TGT_FRAUD_ALERT;


SELECT * 
FROM TGT_REJECT_TRANSACTIONS;

SELECT * 
FROM TGT_RECONCILIATION_ISSUE;

CREATE TABLE TGT_BRANCH_TRANSACTION_SUMMARY (
    BRANCH_NAME VARCHAR2(100),
    TOTAL_TRANSACTIONS NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),
    AVERAGE_AMOUNT NUMBER(12,2),
    MAX_TRANSACTION NUMBER(12,2)
);